box/box-openapi

v2.0/attributes/fields.yml
I'd noted that while you can describe a fields parameter as a string, a more accurate way to describe it is an a non-exploded array of strings.
Update the fields.yml file with the alternate presentation.
=> fix(fields): describe fields as an unexploded array

content/paths/search__get_search.yml
Generic limit documentation referred to limit as default 100, max 1000.
The correct values are default 30, max 200 for search.
Changed this from a generic attribute to a one off limit as I believe this is the only place that the limit is 30/200.
=> Removed generic limit reference and added custom variation to correct limit docs

content/attributes/collaboration_can_view_path.yml, content/paths/collaborations__post_collaborations.yml, content/paths/collaborations__put_collaborations_id.yml
- Add missing can_view_path option back to create and update collaboration endpoints. 
- Use centralized can_view_path attribute object.
- Remove fields query param (DDOC-256).
=> Re-add can_view_path attribute to POST / PUT collaboration calls

content/paths/shared_links__get_shared_items.yml, src/spectral/ensureSchemaHasType.js
Correct the response type for the shared links API. It returns a file or folder.
=> Fix: return correct type of shared links API

content/attributes/skill_card.yml, content/attributes/skill_id.yml, content/callbacks/skill_invocation.yml, content/callbacks/webhook_invocation.yml, content/paths.yml, content/paths/downloads__get_files_id_content.yml, content/paths/skills__delete_files_id_metadata_global_boxSkillsCards.yml, content/paths/skills__get_files_id_metadata_global_boxSkillsCards.yml, content/paths/skills__post_files_id_metadata_global_boxSkillsCards.yml, content/paths/skills__put_files_id_metadata_global_boxSkillsCards.yml, content/paths/skills__put_skill_invocations_id.yml
Adds dedicated API docs for Box Skills. Before this the existing docs were out of date and rolled into the generic metadata docs.
=> Add dedicated API docs for Skills

content/attributes/shared_link-writable.yml
Fixes incorrect documentation regarding setting a shared link to its default access level.
Re `DDOC-353`
=> Fix shared link access level documentation

.spectral.yml, content/paths/metadata_cascade_policies__post_metadata_cascade_policies.yml, content/paths/search__get_search.yml, content/responses/metadata_cascade_policy.yml, content/responses/metadata_field_filter_date_range.yml, content/responses/metadata_field_filter_float.yml, content/responses/metadata_field_filter_float_range.yml, content/responses/metadata_field_filter_multi_select.yml, content/responses/metadata_field_filter_string.yml, content/responses/metadata_filter.yml, content/responses/search_results.yml, content/schemas.yml, src/spectral/ensurePropertiesExample.js
Attempts to improve the search API to better document the `mdfilters` param.
* adds a new Spectral rule to check example of oneOf/anyof fields
* marks query as only required of mdfilters not set
* improves examples
* extracts mdfilters into own object
* extract different variants of `mdfilters.filters` into seperate field filter objects
Re DDOC/356
Re DDOC/317
Estimated go-live 28.8
=> Improve search specficiation regarding metadata filters

content/paths/list_collaborations__get_files_id_collaborations.yml, content/paths/list_collaborations__get_folders_id_collaborations.yml
Add clarification to file/folder collab endpoints to specifically state that pending collaborations are returned
=> Add clarification to file/folder collab endpoints

content/requests/metadata_query.yml
The `use_index` parameter on a metadata query search request is no longer in use. Use of the parameter will be ignored and instead the MDQ service will choose the most efficient index to use from those available. This PR removes the `use_index` parameter from the endpoint definition.
Fixes `DDOC-395`
=> Remove use_index from MDQ search request

content/requests/post_oauth2_token.yml
Updated token documentation in guides and api reference to add:
box_shared_link
OPTIONAL. A canonical URL that represents a link to a file or folder on Box. Password protected links are not supported in the first iteration. Vanity links may be used. Cannot co-exist with "resource". Cannot use a shared link created on a weblink.
`[DDOC-# 191]`(https://jira.inside-box.net/browse/DDOC-191)
Test Results:
=> Ddoc 191 token downscoping

content/errors/client_error.yml
this adds context_info to the list of error response options. 
Re `DDOC-#450` https://jira.inside-box.net/browse/DDOC-450
=> adding context info

content/responses/file_request.yml
Fix url format to better reflect what is returned from the API (lack of protocol and hostname). See also [Java SDK change
](https://github.com/box/box-java-sdk/pull/906)
=> Fix url in File Request response

content/attributes/marker_pagination_without_prev_marker.yml, content/attributes/marker_without_usemarker.yml, content/paths/retention_policies__get_retention_policies.yml, content/paths/retention_policy_assignments__get_retention_policies_id_assignments.yml, content/responses/retention_policies.yml, content/responses/retention_policy_assignments.yml
EG-9092: https://jira.inside-box.net/browse/EG-9092
-Added new marker attribute that doesn't have a line about needing usemarker to be true.
-Added limit, fields, and the new marker attribute to the query parameters of the get retention policies schema.
-Added fields and replaced the older marker attribute with the new one to the query parameters of the get retention policy assignment schemas.
-Added a new marker for pagination attribute that doesn't have a prev_marker entry and has a string as the next_marker type.
-Added the new marker for pagination to the Retention Policies response schema and removed total_count.
-Replaced the older marker with the new marker for pagination to the Retention Policy Assignments response schema and removed total_count.
=> Eg 9092 add limit marker fields to get retention policies

content/attributes/lock.yml
Locks may be held by an application rather than an individual user. The
application is responsible for mediating access to the file. Identify
the owning application to enable clients to show different UI.
Re APIWG-266
=> Identify application-owned locks

content/paths/uploads__post_files_content.yml
This PR adds the missing `400` error response for `uploads/post_files_content` referenced from https://github.com/box/box-openapi/blob/main/content/paths/folders__post_folders.yml as this exhibits the same behaviour as `folders/post_folders`, specifically regarding the naming of the object being created.
Feel free to add anything that may have not already been included, thank you.
=> doc/uploads/post_files_content: Add missing `400` error response

content/paths/folders__delete_folders_id.yml
This PR updates the `delete_folders_id` doc by moving the `folder_not_empty` error to be under `400`, from `409`.
```
HTTP/1.1 DELETE on https://api.box.com/2.0/folders/x responded 400 400 Bad Request ("{\"type\":\"error\",\"status\":400,\"code\":\"folder_not_empty\",\"help_url\":\"http:\\/\\/developers.box.com\\/docs\\/#errors\",\"message\":\"Cannot delete - folder not empty\",\"request_id\":\"x\"}")
```
=> doc/folders/delete_folders_id: Move `folder_not_empty` error from `409` to `400`

content/paths/email_aliases__post_users_id_email_aliases.yml
DDOC-597:  Add a note about domain restriction on email_aliases endpoint
> Note: The domain of the email alias needs to be registered to your enterprise. See this for steps to add a new domain: https://support.box.com/hc/en-us/articles/4408619650579-Domain-Verification
Re `DDOC-597` (`Jira` ticket)
=> Ddoc 597 note email alias

content/responses/file_version--base.yml, content/responses/file_version--full.yml, content/schemas.yml
This field is already supported in the java-sdk, and now windows-sdk support has also been added https://github.com/box/box-windows-sdk-v2/pull/820, but it was missing from open-api specs. I have also extracted fileversion--full, as this field must be required by the `fields` parameter.
=> add `version_number` to `file_version`

content/attributes/file_permissions.yml, content/attributes/folder_permissions.yml, content/attributes/path_collection.yml, content/attributes/path_collection_trash.yml, content/attributes/permissions.yml, content/attributes/shared_link.yml, content/responses/classification_template.yml, content/responses/file--base.yml, content/responses/file--full.yml, content/responses/file--mini.yml, content/responses/file.yml, content/responses/file_request.yml, content/responses/file_version--base.yml, content/responses/folder--base.yml, content/responses/folder--full.yml, content/responses/folder.yml, content/responses/folder_lock.yml, content/responses/metadata_query_index.yml, content/responses/metadata_template.yml, content/responses/retention_policy--base.yml, content/responses/trash_file.yml, content/responses/trash_file_restored.yml, content/responses/trash_folder.yml, content/responses/trash_web_link_restored.yml, content/responses/user--base.yml, content/responses/user--mini.yml, content/responses/web_link--base.yml, content/schemas/event_source.yml, docs/boxers.md
This PR will add a **required** Array with properties which are already marked as non-nullable.
This way TS types generated using [openapi-typescript](https://github.com/drwpow/openapi-typescript)
[related issue regarding required types](https://github.com/drwpow/openapi-typescript/issues/758)
https://jira.inside-box.net/browse/DDOC-607
=> feat: Require non-nullable fields [DDOC-607]

content/paths.yml, content/paths/retention_policies__post_retention_policies.yml, content/paths/retention_policies__put_retention_policies_id.yml, content/paths/retention_policy_assignments__delete_retention_policy_assignments_id.yml, content/paths/retention_policy_assignments__post_retention_policy_assignments.yml, content/responses/retention_policy--mini.yml, content/responses/retention_policy.yml
New docs:
Add DELETE endpoint to retention policy assignments docs: https://staging.developer.box.com/reference/delete-retention-policy-assignments-id/
Updates: 
- Added `retention_type` parameter to POST request for retention policies: https://staging.developer.box.com/reference/post-retention-policies/
- Added `retention_type` and `retention_length` parameters to PUT request for retention policies: https://staging.developer.box.com/reference/put-retention-policies-id/
- Added `retention_type` to the standard response. Mini and base responses stay the same. 
https://staging.developer.box.com/reference/resources/retention-policy/
Fixes DDOC-485
=> DDOC-485: Add params and endpoints for retention policies 

content/errors/client_error.yml
Fix link in error response (https://developer.box.com/reference/resources/client-error/)
Fixes DDOC-666
=> DDOC-666: Fix link in error response

content/schemas/sign_request_create_signer.yml
Add login-required parameter to guides and open API specs in developer documentation.
#[DDOC-677](https://jira.inside-box.net/browse/DDOC-677)
=> Add login-required parameter to dev docs

content/requests/sign_request_create_request.yml
Changed the `File` resource variant from mini to base.
Preview: https://staging.developer.box.com/reference/post-sign-requests/
Fixes DDOC-710
=> DDOC-710: Change variant from Mini to Base

content/requests/sign_request_create_request.yml, content/responses/sign_request.yml
Add missing parameters to the sign request response / request objects:
`signature_color`
`name`
Staging preview: 
https://staging.developer.box.com/reference/resources/sign-request/
https://staging.developer.box.com/reference/post-sign-requests/
Fixes: DDOC-692
=> DDOC-692: Added missing parameters to sign request

content/requests/sign_request_create_request.yml
Minimum value for sign request parameter `days_valid` has range of 0-730.
Changed the min. value.
#[DDOC-660](https://jira.inside-box.net/browse/DDOC-660)
=> days_valid minimum value is 0

content/schemas/sign_request_signer_input.yml
Add value 'attachment' to signer input schema - [[inputs].content_type](https://developer.box.com/reference/resources/sign-request/#param-signers-inputs-content_type)
Solves [DDOC-711](https://jira.inside-box.net/browse/DDOC-711)
=> Add value 'attachment' to signer input schema

content/paths/files__get_files_id.yml, content/responses/retention_policy_assignment.yml
DDOC-757:  make `x-rep-hints` param optional
DDOC-769: Fix `start_date_field` description for retention policy assignment resource
Fixes DDOC-757, DDOC-769
=> DDOC-757-DDOC-769: Fix field description and parameter 

.github/workflows/ci.yml
Pushing content to en branch didn't work properly. The issue is the runner image: https://github.com/actions/runner-images/blob/ubuntu22/20230305.1/images/linux/Ubuntu2204-Readme.md that has node version 18, and it causes issues with webpack.
To fix this we need to override the Node version in the workflow.
Fixes DDOC-793
=> Fix issues with deploying content to EN / STAGING branches

content/requests/sign_request_create_request.yml
File variant for creating sign requests should be base, not mini - as source_files param returns just ID and type fields.
=> Fix file variant - Base instead of Mini

content/responses/file--mini.yml, content/responses/file.yml, content/responses/folder.yml, content/responses/user--mini.yml, content/responses/user_collaborations.yml
Turned required fields params in standard and mini responses to optional for the CodeGen to work properly. These specific parameters are values for fields parameter and do not have to be be marked as required.
Fixes DDOC-825
=> DDOC-825: Make required fields optional

content/paths/trashed_items__get_folders_trash_items.yml
Removed "id" parameter example from the following endpoint: [get-folders-trash-items](https://developer.box.com/reference/get-folders-trash-items/) 
Solves [DDOC-672](https://jira.inside-box.net/browse/DDOC-672)
=> fix: DDOC-672 Remove "id" parameter

.spelling, content/attributes/shared_link-writable.yml, content/paths/shared_links_files__put_files_id--add_shared_link.yml, content/paths/shared_links_files__put_files_id--update_shared_link.yml, content/paths/shared_links_folders__put_folders_id--add_shared_link.yml, content/paths/shared_links_folders__put_folders_id--update_shared_link.yml, content/paths/shared_links_web_links__put_web_links_id--add_shared_link.yml, content/paths/shared_links_web_links__put_web_links_id--update_shared_link.yml, content/paths/web_links__post_web_links.yml, content/paths/web_links__put_web_links_id.yml
Update `shared_link.password` parameter with new requirements.
Fixes `DDOC-841`
=> fix: DDOC-841: Add info about enhanced password

content/paths/folders__get_folders_id_items.yml
Updated description of `sort` param for List Folder Items API to include the sorting behavior for items in shared folders with parent path visible to the user.
Staging: https://staging.developer.box.com/reference/get-folders-id-items/#param-sort
Fixes # DDOC-822
=> fix: DDOC-822:  Update description of `sort` param for List Folder Items API

content/attributes/sort.yml, content/paths/folders__get_folders_id.yml, content/paths/folders__get_folders_id_items.yml, src/spectral/ensurePropertiesExample.js, src/spectral/ensureSchemaHasType.js, src/spectral/ensureSimpleDescription.js
Added the `sort`, `limit`, `offset`, and `direction` query params to the GET folders endpoint.
Fixes `DDOC-854`
On staging: https://staging.developer.box.com/reference/get-folders-id/
Additional changes: improved spectral / linter messages wording
=> fix: DDOC-854: Add query params for GET folders endpoint

content/responses/sign_request.yml
Add `finalizing` and `error_finalizing` status to  https://developer.box.com/reference/resources/sign-request/#param-status
Fixes DDOC-856
=> feat: DDOC-856 add `finalizing` and `error_finalizing` status to Sign Request resource

content/responses/search_results.yml, content/responses/search_results_with_shared_links.yml
Search endpoints can return two types of results. Add "type" field at root search response to easly determine which kind it is.
APIWG-349
=> feat: APIWG-349 add search response type at root result

content/paths/zip_downloads__post_zip_downloads.yml
Added note about recommended maxiumum ZIP archive size
Fixes DDOC-862
Staging preview: https://staging.developer.box.com/reference/post-zip-downloads/
=> fix: DDOC-862: Add note on recommended ZIP archive size

content/paths/files__put_files_id.yml, content/paths/folders__put_folders_id.yml
Missing collections schema from PUT files endpoint. It is already referenced in the guides https://developer.box.com/guides/collections/add/. Basically same as for Folders - https://developer.box.com/reference/put-folders-id/#param-collections
=> feat: add collections to PUT files endpoint

content/paths/web_links__post_web_links.yml
Remove share link param from POST, because shared links are created with PUT, POST doesn't work.
Fixes DDOC-861
=> fix: DDOC-861: Remove share link param from POST

content/responses/metadata--full.yml
type is required on additionalProperties https://swagger.io/docs/specification/data-models/dictionaries/
=> fix: Update metadata--full.yml to include type on additionalProperties

content/paths/collaborations__post_collaborations.yml, content/paths/comments__post_comments.yml, content/paths/tasks__post_tasks.yml
Marked `item.id` and `item.type` fields for comments (https://developer.box.com/reference/post-comments/) endpoint as required.
Staging: https://staging.developer.box.com/reference/post-comments/
Fixes DDOC-868
=> fix: DDOC-868: mark fields as required

content/attributes/metadata_field--readable.yml, content/responses/metadata_template.yml
Added the `integer` value to metadata template response (only, not present in the request on purpose) along with the note that it is deprecated.
=> fix: Add `integer` value to metadata template response

.spelling, content/schemas/integration_mapping_partner_item_slack.yml
Add more information to `slack_workspace_id` and `slack_org_id` params for integration mappings.
Staging preview: https://staging.developer.box.com/reference/post-integration-mappings-slack/#param-partner_item
Fixes # DDOC-871
=> fix: DDOC-871: add info on params for mappings

content/paths/file_metadata__get_files_id_metadata_id_id.yml, content/paths/memberships__post_group_memberships.yml, content/paths/memberships__put_group_memberships_id.yml, content/schemas/sign_request_signer.yml
Add iframeable_embed_url param to box sign request to provide support for signing documents within an HTML iframe tag.
staging: https://staging.developer.box.com/reference/resources/sign-request/#param-signers-iframeable_embed_url
A part of DDOC-855 (along with guide improvements and changelog entry).
=> feat: DDOC-855 add iframeable_embed_url param to box sign request

content/paths/storage_policies__get_storage_policies.yml, content/paths/storage_policies__get_storage_policies_id.yml, content/paths/storage_policy_assignments__delete_storage_policy_assignments_id.yml, content/paths/storage_policy_assignments__get_storage_policy_assignments.yml, content/paths/storage_policy_assignments__get_storage_policy_assignments_id.yml, content/paths/storage_policy_assignments__post_storage_policy_assignments.yml, content/paths/storage_policy_assignments__put_storage_policy_assignments_id.yml
Add information about the storage policy endpoints: 
- can be accessed only by primary Admin
- user needs to generate a token for an account to authenticate the request
Closed [DDOC-690](https://jira.inside-box.net/browse/DDOC-690)
=> docs: Storage policies: endpoints only accessible by admin

content/responses/search_results.yml, content/responses/search_results_with_shared_links.yml, openapi.json
Needed for correct deserialization of search response in box-typescript-sdk-gen
=> fix: mark type as required in search results

.github/ISSUE_TEMPLATE/docs_error.yaml, .github/PULL_REQUEST_TEMPLATE.md
=> fix: change description of two fields in docs issue template

openapi.json
This reverts commit 0a29c66a1f49ca3887852a73cec5b7c74f10fc11.
=> Revert "fix: Update storage policy assignments (#394)"

openapi.json
Add `is_active` param to user collaborations
=> feat: Add `is_active` param to user collab

openapi.json
Removing `is_phone_verification_required `param from all Box Sign resources. This parameter will be true by default from now on and as such doesn't need to be visible in responses.
Closes [DDOC-1088](https://jira.inside-box.net/browse/DDOC-1088)
=> docs: remove parameter from Sign page

openapi.json, openapi/openapi-v2025.0.json, openapi/openapi.json
Update response status codes to 200 for security classification endpoints.
Update folder and file name restrictions in API specifications.
Closes:
https://github.com/box/box-openapi/issues/436
https://github.com/box/box-openapi/issues/371
=> fix: Fix issues in box-openapi
