box/box-openapi

- v2.0/openapi-v2.json
- v2.0/token.openapi-v2.json
- v2.0/upload.openapi-v2.json
1. createUploadSession
2. createUploadSessionNewVersion
3. getUploadSession
4. uploadPart
5. abortUploadSession
6. listParts
7. commitUploadSession
> Swagger spec for SuperchargedUpload API

- v2.0/upload.openapi-v2.json
> Correct string value of 'required' property

- v2.0/upload.openapi-v2.json
Swaps upload parameter order as API documentation suggests to close Issue #12
> changed order of parameters

- v2.0/paths/task_assignments__delete_task_assignments_id.yml
- v2.0/paths/task_assignments__get_task_assignments_id.yml
- v2.0/paths/task_assignments__get_tasks_id_assignments.yml
- v2.0/paths/task_assignments__put_task_assignments_id.yml
- v2.0/paths/tasks__delete_tasks_id.yml
- v2.0/paths/tasks__get_files_id_tasks.yml
- v2.0/paths/tasks__get_tasks_id.yml
- v2.0/paths/tasks__put_tasks_id.yml
- yarn.lock
Yarn.lock also updated. I can remove that from the commit if we don't want it merged in.
> Add 404 response codes to Tasks API 

- v2.0/paths/tasks__post_tasks.yml
- v2.0/paths/tasks__put_tasks_id.yml
- v2.0/resources/task.yml
Add new completion rule value to the task object
> Add new completion_rule value to task object

- package.json
- v2.0/paths/groups__post_groups.yml
- v2.0/paths/groups__put_groups_id.yml
- v2.0/paths/users__post_users.yml
- v2.0/paths/users__put_users_id.yml
- v2.0/resources/user.yml
- yarn.lock
Reading the release of the new developer site and merging all staging changes.
> Merging staging changes

- v2.0/attributes/direction.yml
- v2.0/attributes/marker.yml
- v2.0/paths/folders__get_folders_id_items.yml
- v2.0/paths/trashed_items__get_folders_trash_items.yml
Note: do not merge until approved.
> Add marker based pagination to the trash API

- content/attributes/collaboration_can_view_path.yml
Re. https://github.com/box/box-openapi/pull/66#pullrequestreview-339403551
> Bold all files and state 1000 can_view_path suggestion as per user

- content/paths/events__get_events.yml
Internal ticket reference: DDOC-291
> Add OAuth 2 token revoke event

- content/attributes/shared_link.yml
- content/paths/search__get_search.yml
Improvements and clarifications to the Box Search API spec.
> Update search API copy and descriptions

- content/attributes/search_result_collection.yml
- content/paths/search__get_search.yml
- content/responses/search_result_with_shared_link.yml
- content/responses/search_results.yml
- content/responses/search_results_with_shared_links.yml
- content/schemas.yml
> Add shared links to search results

- content/paths/folder_locks__post_folder_locks.yml
- content/requests/post_oauth2_token.yml
DDOC-373
- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own changes
- [X ] I have run `yarn lint` to make sure my changes pass all linters
- [X ] I have pulled the latest changes from the upstream developer branch
> Add client credential grant token request

- content/requests/post_oauth2_token.yml
DDOC-376 
- [X ] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own changes
- [ X] I have run `yarn lint` to make sure my changes pass all linters
- [X ] I have pulled the latest changes from the upstream developer branch
> Add client credentials to client id and client secret

- content/responses/search_result_with_shared_link.yml
Add new type field to search results with shared link response object.
Fixes # `DDOC-394`
> Add new type field

- content/paths/transfer__put_users_id_folders_0.yml
ddoc-429 
- [X ] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own changes
- [ X] I have run `yarn lint` to make sure my changes pass all linters
- [X ] I have pulled the latest changes from the upstream developer branch
> Clarify single file collaboration behavior during transfer

- content/paths/shared_links_files__put_files_id--add_shared_link.yml
- content/paths/shared_links_files__put_files_id--update_shared_link.yml
- content/paths/shared_links_folders__put_folders_id--add_shared_link.yml
- content/paths/shared_links_folders__put_folders_id--update_shared_link.yml
> Add minimum unshare at value

- content/attributes/uploader_display_name.yml
> Fix file request naming information

- content/paths/workflows__get_workflows.yml
- content/paths/workflows__post_workflows_id_start.yml
- content/responses/workflow--full.yml
- content/responses/workflow--mini.yml
- content/responses/workflow.yml
- content/responses/workflows.yml
This fixed issues from the recent manual start relay release.
> fixing typo and adding setting

- content/requests/sign_request_create_request.yml
- content/schemas/sign_request_create_signer.yml
> Sign request updates

- content/paths/folder_locks__delete_folder_locks_id.yml
- content/paths/folder_locks__get_folder_locks.yml
- content/paths/folder_locks__post_folder_locks.yml
> Ddoc 387 folder lock

- content/paths/search__get_search.yml
> updating the tags field

- content/paths/search__get_search.yml
> adding new field

- content/attributes/access_token--skill_invocation.yml
- content/callbacks/skill_invocation.yml
Added a new access-token--skill_invocation attribute with correct value for `token.restricted_to` parameter
Linked then new attribute in the `skill_invocation.yml` file.
Fixes
`DDOC-571`
> DDOC-571: Improve skills response

- content/paths/authorization__get_authorize.yml
Expanded the `redirect_uri` parameter description to include info on handling multiple redirect URIs.
https://staging.developer.box.com/reference/get-authorize/
Fixes `DDOC-555`
> DDOC-555:  Add content to redirect_uri parameter

- content/attributes/shared_link.yml
- content/common/tags.yml
- content/paths.yml
- content/paths/shared_links_files__get_files_id--get_shared_link.yml
- content/paths/shared_links_files__get_shared_items.yml
- content/paths/shared_links_files__put_files_id--add_shared_link.yml
- content/paths/shared_links_files__put_files_id--update_shared_link.yml
- content/paths/shared_links_folders__get_folders_id--get_shared_link.yml
- content/paths/shared_links_folders__put_folders_id--add_shared_link.yml
- content/paths/shared_links_folders__put_folders_id--update_shared_link.yml
- content/paths/shared_links_web_links__get_shared_items--web_links.yml
- content/paths/shared_links_web_links__get_shared_items.yml
- content/paths/shared_links_web_links__get_web_links_id--get_shared_link.yml
- content/paths/shared_links_web_links__put_web_links_id--add_shared_link.yml
- content/paths/shared_links_web_links__put_web_links_id--remove_shared_link.yml
- content/paths/shared_links_web_links__put_web_links_id--update_shared_link.yml
- content/responses/file--full.yml
> Ddoc 437 esl

- content/responses/event.yml
Added the following params to Event API ref:
`created_at`
`recorded_at`
Fixes DDOC-547
> DDOC-574 add parameters to Event API ref

- content/attributes/file_id.yml
- content/paths.yml
- content/paths/avatars__delete_users_id_avatar.yml
- content/paths/avatars__post_users_id_avatar.yml
- content/paths/file_watermarks__delete_files_id_watermark.yml
- content/responses/user_avatar.yml
- content/schemas.yml
Added the following endpoints:
- POST user avatar
- DELETE user avatar
Preview:https://staging.developer.box.com/reference/resources/user-avatar/
Fixed minor issues in other docs 
Fixes DDOC-496
> DDOC-496: Add endpoints for user avatars

- content/paths/avatars__post_users_id_avatar.yml
Updated error description for uploading user avatars.
> DDOC-496: Add error desc avatar docs

- content/attributes/shared_link.yml
Updated description on shared link permissions and effective permissions, clarifying the differences.
DDOC-603 ESL Fast Follows
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own changes
- [x ] I have run `yarn lint` to make sure my changes pass all linters
- [x ] I have pulled the latest changes from the upstream developer branch
> Ddoc 603/esl fast follows

- content/attributes/shared_link.yml
- content/responses/sign_request.yml
- content/responses/sign_requests.yml
- content/schemas/sign_request_signer_input.yml
> Ddoc 561 box sign fields

- content/paths/collaborations__post_collaborations.yml
- content/responses/collaboration.yml
Remove `is_access_only` mentions.
> Revert changes in collab API ref

- content/paths/folders__put_folders_id.yml
Added `operation_limit_exceeded` 403 response for `put folders` endpoint. 
Fixes [#DDOC-611](https://jira.inside-box.net/browse/DDOC-611)
> Added 403 response description

- .spelling
- content/attributes/content_range.yml
- content/attributes/digest.yml
Upload the openAPI reference to add more context on how to upload file parts.
Affected docs:
https://staging.developer.box.com/reference/put-files-upload-sessions-id/
> DDOC-656: Update upload part API ref

- content/attributes/skill.yml
Added missing type on Skill schema.
> add missing type to Skill

- content/paths/search__get_search.yml
Updated search API with deleted_user_ids and deleted_at_range string arrays.
Solves [DDOC-796](https://jira.inside-box.net/browse/DDOC-796)
> Add new strings to search API

- .github/workflows/ci.yml
- content/paths/comments__get_comments_id.yml
- content/paths/comments__put_comments_id.yml
- content/paths/file_versions__get_files_id_versions_id.yml
- content/paths/file_versions__post_files_id_versions_current.yml
- content/paths/file_versions__put_files_id_versions_id.yml
- content/paths/files__get_files_id.yml
- content/paths/files__post_files_id_copy.yml
- content/paths/files__put_files_id.yml
- content/paths/folders__get_folders_id.yml
- content/paths/folders__post_folders.yml
- content/paths/folders__post_folders_id_copy.yml
- content/paths/folders__put_folders_id.yml
- content/paths/groups__get_groups_id.yml
- content/paths/groups__put_groups_id.yml
- content/paths/shared_links_files__get_files_id--get_shared_link.yml
- content/paths/shared_links_files__get_shared_items.yml
- content/paths/shared_links_files__put_files_id--add_shared_link.yml
- content/paths/shared_links_files__put_files_id--remove_shared_link.yml
- content/paths/shared_links_files__put_files_id--update_shared_link.yml
- content/paths/shared_links_folders__get_folders_id--get_shared_link.yml
- content/paths/shared_links_folders__get_shared_items--folders.yml
- content/paths/shared_links_folders__put_folders_id--add_shared_link.yml
- content/paths/shared_links_folders__put_folders_id--remove_shared_link.yml
- content/paths/shared_links_folders__put_folders_id--update_shared_link.yml
- content/paths/transfer__put_users_id_folders_0.yml
- content/paths/users__get_users_id.yml
- content/paths/users__get_users_me.yml
- content/paths/users__put_users_id.yml
Replaced Standard variants with Full variants in response for endpoints with fields parameter. 
Fixes `DDOC-764
> DDOC-764: Add Full variants in response for endpoints with fields parameter

- content/attributes/sequence_id.yml
- content/responses/folder--mini.yml
- src/spectral/ensureAllOfOrder.js
`sequence_id` param should be nullable.
Additionally - temporary deactivate one of spectral rules for tests.
> Make `sequence_id` param nullable

- content/responses/folder--mini.yml
> Remove redundant ref

- content/paths/search__get_search.yml
Added `all_items` param value to `trash_content` param.
Re `DDOC-826
> feat: add param value to `trash_content` (DDOC-826)

- .github/workflows/ci.yml
Add step into the workflow to validate the OpenAPI specs.
> chore: Update workflow to validate OpenAPI specification

- content/attributes/shared_link-writable.yml
- content/paths/shared_links_files__put_files_id--add_shared_link.yml
- content/paths/shared_links_files__put_files_id--update_shared_link.yml
- content/paths/shared_links_folders__put_folders_id--add_shared_link.yml
- content/paths/shared_links_folders__put_folders_id--update_shared_link.yml
- content/paths/shared_links_web_links__put_web_links_id--add_shared_link.yml
- content/paths/shared_links_web_links__put_web_links_id--update_shared_link.yml
- content/paths/web_links__post_web_links.yml
- content/paths/web_links__put_web_links_id.yml
> docs: Fix wording

- content/paths/downloads__get_files_id_content.yml
- content/paths/files__get_files_id_thumbnail_id.yml
Added the 200 response to download file api.
staging preview: https://staging.developer.box.com/reference/get-files-id-content/#param-200-application/octet-stream
Fixes # DDOC-865
> fix: DDOC-865: Add 200 response to download file api

- .github/ISSUE_TEMPLATE/docs_error.yaml
- .github/PULL_REQUEST_TEMPLATE.md
Please include a summary of the change and which issue is fixed. 
> feat: add docs issue template

- content/responses/collaboration.yml
- content/responses/group--base.yml
- openapi.json
> fix: change `accessible_by` in Collaboration to allow setting `Group-Mini`

- openapi.json
> fix: Revert "feat: pull specification from public api (#367)"

- content/schemas/sign_request_signer.yml
Added `additional_info` param to `signer_decision`
Fixes DDOC-909
> feat: DDOC-909: add additional_info param

- .github/workflows/ci.yml
> feat: run codegen generate command to validate API spec

- .alexrc.json
> chore: Add missing items to .alexrc.json

- openapi.json
> fix: DDOC-1055- Fix AI Endpoints 

- .github/workflows/ci.yml
- README.md
> fix: (APIMGMT-407) Remove Swagger 

- .spelling
> chore: update spelling linter exceptions

- openapi.json
> fix: remove redundant user_id

- .github/workflows/ci.yml
> ci: Validate multiple OpenAPI files on codegen validation pipeline
